<a href="https://colab.research.google.com/github/felixmd/machinelearning/blob/master/reference/CUDASemantics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Basic CUDA semeantics (*requires GPU*). 

In [1]:
import torch  

In [2]:
torch.cuda.is_available()

True

In [3]:
torch.cuda.init()

In [4]:
torch.cuda.current_device()

0

In [5]:
torch.cuda.device_count()

1

In [6]:
torch.cuda.memory_allocated()

0

In [7]:
torch.cuda.memory_cached()

0

In [8]:
selected_device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
selected_device

device(type='cuda')

In [9]:
cuda0 = torch.device('cuda:0')
cuda1 = torch.device('cuda:1')
cuda0, cuda1

(device(type='cuda', index=0), device(type='cuda', index=1))

In [10]:
random_tensor = torch.rand(5)
random_tensor

tensor([0.2614, 0.7623, 0.5118, 0.1168, 0.4409])

In [11]:
random_tensor_gpu = torch.randn(5, device=selected_device)
random_tensor_gpu.device

device(type='cuda', index=0)

In [12]:
random_tensor_gpu

tensor([ 0.5684,  0.2536, -0.4118, -1.0579,  0.5143], device='cuda:0')

In [13]:
random_tensor_gpu.to(cuda0)
random_tensor_gpu

tensor([ 0.5684,  0.2536, -0.4118, -1.0579,  0.5143], device='cuda:0')

In [14]:
#copy non-cuda tensor to CUDA memory 
tensor_copy_to_GPU = random_tensor.cuda()
tensor_copy_to_GPU

tensor([0.2614, 0.7623, 0.5118, 0.1168, 0.4409], device='cuda:0')

In [15]:
torch.cuda.memory_allocated()

1024

In [16]:
torch.cuda.memory_cached()

2097152

In [17]:
torch.cuda.empty_cache()
torch.cuda.memory_cached()

2097152

In [20]:
preserve_context = random_tensor_gpu.new_full([2,2],fill_value=3.5)
preserve_context

tensor([[3.5000, 3.5000],
        [3.5000, 3.5000]], device='cuda:0')