<a href="https://colab.research.google.com/github/felixmd/machinelearning/blob/master/reference/PytorchTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = "1"

In [3]:
import torch

print(torch.__version__)

1.5.1+cu101


In [4]:
torch.get_default_dtype()

torch.float32

In [5]:
torch.set_default_dtype(torch.float64)
torch.get_default_dtype()

torch.float64

In [6]:
tensor_arr = torch.Tensor([[2,5,6],[9,7,6]])
tensor_arr

tensor([[2., 5., 6.],
        [9., 7., 6.]])

In [7]:
torch.is_tensor(tensor_arr)

True

In [8]:
#print number of elements
torch.numel(tensor_arr)

6

In [9]:
random_tensor = torch.randint(5,100,(2,3))
random_tensor

tensor([[78, 96, 89],
        [62, 87, 40]])

In [10]:
un_initialized = torch.Tensor(2,2)
un_initialized

tensor([[4.2019e-316, 4.2056e-316],
        [ 0.0000e+00, 1.7383e-310]])

In [11]:
tensor_fill = torch.full((2,6), fill_value=10, dtype=torch.int64)
tensor_fill

tensor([[10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10]])

In [12]:
tensor_of_zeros = torch.zeros_like(tensor_fill)
tensor_of_zeros

tensor([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]])

In [13]:
tensor_eye = torch.eye(7, dtype=torch.int16)
tensor_eye

tensor([[1, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 1]], dtype=torch.int16)

In [14]:
non_zero_elements = torch.nonzero(tensor_eye, as_tuple=False)
non_zero_elements

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4],
        [5, 5],
        [6, 6]])

When a matrix, array, or tensor has lots of values that are zero, it can be called sparse. You might want to represent the zeros implicitly with a sparse representation. A sparse representation of the tensor will focus only on the non-zero values.



In [15]:
index_tensor = torch.tensor([[0,1,1],
                             [2,2,0]])
value_tensor = torch.tensor([3,4,5],dtype=torch.float32)
sparse_tensor = torch.sparse_coo_tensor(index_tensor, value_tensor, [2,5])
sparse_tensor
#Index 0,2 will have value 3, index 1,2 will have value 4 and index 1,0 will have value 5

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3., 4., 5.]),
       size=(2, 5), nnz=3, dtype=torch.float32, layout=torch.sparse_coo)

In [16]:
sparse_tensor.to_dense()

tensor([[0., 0., 3., 0., 0.],
        [5., 0., 4., 0., 0.]], dtype=torch.float32)

In [17]:
in_place_tensor = torch.zeros(2,2)
in_place_tensor.fill_(10)
in_place_tensor

tensor([[10., 10.],
        [10., 10.]])

In [18]:
added_tensor = in_place_tensor.add(15)

added_tensor

tensor([[25., 25.],
        [25., 25.]])

In [19]:
in_place_tensor

tensor([[10., 10.],
        [10., 10.]])

In [20]:
in_place_tensor.sqrt_()
in_place_tensor

tensor([[3.1623, 3.1623],
        [3.1623, 3.1623]])

In [21]:
spaced_tensor = torch.linspace(5, 100, steps=15)
spaced_tensor.int()

tensor([  5,  11,  18,  25,  32,  38,  45,  52,  59,  66,  72,  79,  86,  93,
        100], dtype=torch.int32)

In [22]:
chunks = torch.chunk(spaced_tensor,4, 0)
chunks

(tensor([ 5.0000, 11.7857, 18.5714, 25.3571]),
 tensor([32.1429, 38.9286, 45.7143, 52.5000]),
 tensor([59.2857, 66.0714, 72.8571, 79.6429]),
 tensor([ 86.4286,  93.2143, 100.0000]))

In [23]:
torch.cat(chunks, 0)

tensor([  5.0000,  11.7857,  18.5714,  25.3571,  32.1429,  38.9286,  45.7143,
         52.5000,  59.2857,  66.0714,  72.8571,  79.6429,  86.4286,  93.2143,
        100.0000])

In [24]:
random_tensor = torch.randint(2,30,(3,3))
random_tensor


tensor([[29,  8, 22],
        [17, 18, 14],
        [15, 13, 13]])

In [25]:
random_tensor[0,1]

tensor(8)

In [26]:
random_tensor[1:,1:]

tensor([[18, 14],
        [13, 13]])

In [27]:
# View as 1-D tensor
random_tensor.view(torch.numel(random_tensor))

tensor([29,  8, 22, 17, 18, 14, 15, 13, 13])